#! /bin/bash
# attention lancer le navigateur avant
# chromium-browser &
export BROWSER="chromium-browser"
#workon ipython2
ipython nbconvert CFM2015.ipynb --to=slides --template output_toggle --post serve --ServePostProcessor.reveal.cdn="http://cdn.jsdelivr.net/reveal.js/2.5.0" --profile=slideshow
#ipython nbconvert CFM2015.ipynb --to=slides --template output_toggle --post serve --profile=slideshow
